export const TeamBehindArray = [
  {
    number: "117+",
    title: "Completed Projects",
    desc: "That,s over 60 times we pat our own back, countless cans of Redbull and a whole lot of Error404.",
  },
  {
    number: "2,730+",
    title: "Hours Pressing Keys",
    desc: "That's like watching “The Godfather” more than 1,000 times, but instead of Don Corleone, it's boring software.",
  },
  {
    number: "$100M+",
    title: "Revenue Generated by Clients",
    desc: "We don't just make websites or grow your online presence, we get Dinero into your pockets, at the end of the day, that's what it's all about.",
  },
];
